version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: GYN2NfBir2PBh-cS5jWlRF62GeripTw_
      POSTGRES_USER: nevgljwz
      POSTGRES_DB: nevgljwz
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - "5432:5432"
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && yarn install --check-files && bundle exec rails assets:precompile && rails db:create && rails db:migrate && bundle exec rails s -e production -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    environment:
      POSTGRES_PASSWORD: GYN2NfBir2PBh-cS5jWlRF62GeripTw_
      POSTGRES_USER: nevgljwz
      POSTGRES_DB: nevgljwz
      RAILS_MASTER_KEY: 23c9fbb22adf45fe8caef931d896f8d1
    depends_on:
      - db
